config/routes.rb
EasyTokens::Engine.routes.draw do
  root to: 'tokens#index'
  resources :tokens, except: [:show, :destroy] do
    get :deactivate_token
  end
end

app/models/easy_tokens/token.rb
module EasyTokens
  class Token < ActiveRecord::Base
    after_initialize :ensure_token_presence
    belongs_to :owner, class_name: EasyTokens.token_owner_class

    private

    def ensure_token_presence
      self.value ||= SecureRandom.hex(16)
    end
  end
end

app/controllers/easy_tokens/application_controller.rb
module EasyTokens
  class ApplicationController < ActionController::Base
  end
end

app/controllers/easy_tokens/tokens_controller.rb
require_dependency 'easy_tokens/application_controller'

module EasyTokens
  class TokensController < ::ApplicationController
    before_action :authorize!
    before_action :set_token, only: [:edit, :update, :destroy]

    layout 'easy_tokens/application'

    def index
      @tokens = Token.all
    end

    def new
      @token = Token.new
    end

    def edit
    end

    def create
      @token = Token.new(token_params)
      @token.owner_id = owner_resource.id

      if @token.save
        redirect_to tokens_path, notice: 'Token was successfully created.'
      else
        render :new
      end
    end

    def update
      if @token.update(token_params)
        redirect_to tokens_path, notice: 'Token was successfully updated.'
      else
        render :edit
      end
    end

    def deactivate_token
      @token = Token.find(params[:token_id])
      @token.touch(:deactivated_at)
      @token.save
      redirect_to tokens_path
    end

    private

    def set_token
      @token = Token.find(params[:id])
    end

    def token_params
      params.require(:token).permit(:description)
    end

    def authorize!
      return if owner_resource.public_send EasyTokens.owner_authorization_method
      render text: 'Unauthorized', status: :unauthorized
    end

    def owner_resource
      @owner_resource ||= send EasyTokens.token_owner_method
    end
  end
end

app/views/easy_tokens/tokens/_form.html.erb
<%= form_for @token, html: { class: "form" } do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <div class="button-group">
    <%= f.submit 'Save', class: "button button--success" %>
    <%= link_to 'Back', tokens_path, class: "button" %>
  </div>
<% end %>

app/views/easy_tokens/tokens/edit.html.erb
<h1>Edit token</h1>

<%= render 'form' %>

app/views/easy_tokens/tokens/index.html.erb
<% if notice.present? %>
  <div class="notice-flash">
    <%= notice %>
  </div>
<% end %>

<h1>Listing tokens</h1>

<table class="table">
  <thead class="table__header">
    <tr>
      <th>Value</th>
      <th>Description</th>
      <th>Owner</th>
      <th>Deactivated at</th>
      <th></th>
    </tr>
  </thead>

  <tbody class="table__body">
    <% @tokens.each do |token| %>
      <tr>
        <td><pre><%= token.value %></pre></td>
        <td><%= token.description %></td>
        <td><%= token.owner %></td>
        <td><%= token.deactivated_at %></td>
        <td>
          <%= link_to 'Edit', edit_token_path(token), class: "button button--warning button--small" %>
          <%= link_to 'Deactivate', token_deactivate_token_path(token), class: "button button--error button--small" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path, class: "button button--primary" %>

app/views/easy_tokens/tokens/new.html.erb
<h1>Create new token</h1>

<%= render 'form' %>

app/views/layouts/easy_tokens/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyTokens</title>
  <%= stylesheet_link_tag    "easy_tokens/application", media: "all" %>
  <%= javascript_include_tag "easy_tokens/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="content">
    <%= yield %>
  </div>
</body>
</html>